apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-lb-failover
  region: us-east-2

iam:
  withOIDC: true   
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true  

managedNodeGroups:
  - name: app-lb-failover-ng
    instanceType: t3.medium
    minSize: 1
    maxSize: 2